# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelectoresfilmaffinity():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_selectoresfilmaffinity(self):
    self.driver.get("https://www.filmaffinity.com/es/main.html")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.CSS_SELECTOR, ".css-113jtbf:nth-child(2) > span").click()
    self.driver.find_element(By.ID, "top-search-input-2").click()
    self.driver.find_element(By.ID, "top-search-input-2").send_keys("nombre")
    self.driver.find_element(By.ID, "top-search-input-2").send_keys(Keys.ENTER)
  
